create extension if not exists pg_cron;
create extension if not exists pg_net;
create extension if not exists vault;

create table if not exists public.ephemerides (
  id bigint generated by default as identity primary key,
  display_date date unique,
  day integer not null,
  month integer not null,
  year integer not null,
  event text not null,
  historical_day integer,
  historical_month integer,
  historical_year integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.ephemerides enable row level security;

drop policy if exists "Public can read ephemerides" on public.ephemerides;
create policy "Public can read ephemerides"
  on public.ephemerides
  for select
  using (true);

drop policy if exists "Service role can write ephemerides" on public.ephemerides;
create policy "Service role can write ephemerides"
  on public.ephemerides
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_ephemerides_updated_at on public.ephemerides;

create trigger set_ephemerides_updated_at
before update on public.ephemerides
for each row
execute function public.set_updated_at();

-- Store these values in Supabase Vault before enabling the schedule:
--   project_url     -> https://<project-ref>.supabase.co
--   publishable_key -> your Supabase publishable/anon key
-- The schedule runs at 06:00 UTC, which is 00:00 in America/Mexico_City.
select
  cron.schedule(
    'generate-next-ephemeris-daily',
    '0 6 * * *',
    $$
    select
      net.http_post(
        url := (select decrypted_secret from vault.decrypted_secrets where name = 'project_url') || '/functions/v1/generate-next-ephemeris',
        headers := jsonb_build_object(
          'Content-Type', 'application/json',
          'apikey', (select decrypted_secret from vault.decrypted_secrets where name = 'publishable_key')
        ),
        body := '{}'::jsonb
      ) as request_id;
    $$
  );
